export type RecommendedSource = {
  id: string;
  name: string;
  topicLabel: string;
  description: string;
  homepageUrl: string;
  feedUrl?: string;
  cadence: string;
  sourceType: "news" | "newsletter";
  sourceFormat: "rss" | "api" | "other";
  importStatus: "ready" | "manual";
  lifecycleStatus: "active_default" | "active_optional" | "catalog_only" | "probationary" | "disabled" | "legacy";
  validationStatus: "validated" | "unverified" | "failed" | "requires_key" | "manual_only";
  mvpDefaultAllowed: boolean;
  editorialPreference: "none" | "approved";
  note?: string;
};

export const recommendedSources: RecommendedSource[] = [
  {
    id: "lennys-newsletter",
    name: "Lenny's Newsletter",
    topicLabel: "Product",
    description: "High-signal product, growth, and operator writing via newsletter RSS.",
    homepageUrl: "https://www.lennysnewsletter.com",
    feedUrl: "https://www.lennysnewsletter.com/feed",
    cadence: "Weekly",
    sourceType: "newsletter",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "catalog_only",
    validationStatus: "unverified",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
  },
  {
    id: "reuters-top-news",
    name: "Reuters Top News",
    topicLabel: "Geopolitics",
    description: "Top global headlines and breaking developments from Reuters.",
    homepageUrl: "https://www.reuters.com",
    feedUrl: "https://feeds.reuters.com/reuters/topNews",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "legacy",
    validationStatus: "failed",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Legacy Reuters RSS endpoint is not validated for current import. Do not promote without a fresh working endpoint check.",
  },
  {
    id: "reuters-business-news",
    name: "Reuters Business",
    topicLabel: "Markets",
    description: "Business, macro, and company news from Reuters Business.",
    homepageUrl: "https://www.reuters.com",
    feedUrl: "https://feeds.reuters.com/reuters/businessNews",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "legacy",
    validationStatus: "failed",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Legacy Reuters RSS endpoint is not validated for current import. Do not promote without a fresh working endpoint check.",
  },
  {
    id: "reuters-technology-news",
    name: "Reuters Technology",
    topicLabel: "AI",
    description: "Technology and AI-adjacent coverage from Reuters Technology.",
    homepageUrl: "https://www.reuters.com",
    feedUrl: "https://feeds.reuters.com/reuters/technologyNews",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "legacy",
    validationStatus: "failed",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Legacy Reuters RSS endpoint is not validated for current import. Do not promote without a fresh working endpoint check.",
  },
  {
    id: "tldr",
    name: "TLDR",
    topicLabel: "AI",
    description: "Curated tech and startup newsletter coverage from TLDR.",
    homepageUrl: "https://tldr.tech",
    feedUrl: "https://tldr.tech/rss",
    cadence: "Daily",
    sourceType: "newsletter",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "probationary",
    validationStatus: "unverified",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
  },
  {
    id: "tldr-ai",
    name: "TLDR AI",
    topicLabel: "AI",
    description: "AI-specific newsletter coverage from TLDR AI.",
    homepageUrl: "https://tldr.tech/ai",
    feedUrl: "https://tldr.tech/ai/rss",
    cadence: "Daily",
    sourceType: "newsletter",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "probationary",
    validationStatus: "unverified",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
  },
  {
    id: "morning-brew",
    name: "Morning Brew",
    topicLabel: "Markets",
    description: "Business and market updates from Morning Brew.",
    homepageUrl: "https://www.morningbrew.com",
    cadence: "Daily",
    sourceType: "newsletter",
    sourceFormat: "other",
    importStatus: "manual",
    lifecycleStatus: "catalog_only",
    validationStatus: "manual_only",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Homepage is available, but feed access appears protected and was not verified for import.",
  },
  {
    id: "alex-rechevskiy",
    name: "Alex Rechevskiy",
    topicLabel: "Product",
    description: "Recent publishing activity from Alex Rechevskiy.",
    homepageUrl: "https://www.linkedin.com/in/alexrechevskiy/recent-activity/all/",
    cadence: "Irregular",
    sourceType: "newsletter",
    sourceFormat: "other",
    importStatus: "manual",
    lifecycleStatus: "catalog_only",
    validationStatus: "manual_only",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "LinkedIn activity pages do not expose a verified RSS feed for the current importer.",
  },
  {
    id: "matt-levine",
    name: "Matt Levine",
    topicLabel: "Markets",
    description: "Opinion and markets commentary from Matt Levine on Bloomberg.",
    homepageUrl: "https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine",
    cadence: "Frequent",
    sourceType: "newsletter",
    sourceFormat: "other",
    importStatus: "manual",
    lifecycleStatus: "catalog_only",
    validationStatus: "manual_only",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Bloomberg author pages were verified, but not a public RSS feed for direct import.",
  },
  {
    id: "a16z",
    name: "a16z",
    topicLabel: "AI",
    description: "Essays, market views, and company perspectives from Andreessen Horowitz.",
    homepageUrl: "https://a16z.com",
    cadence: "Frequent",
    sourceType: "news",
    sourceFormat: "other",
    importStatus: "manual",
    lifecycleStatus: "catalog_only",
    validationStatus: "manual_only",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Homepage verified, but a working public RSS URL was not confirmed.",
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    topicLabel: "AI",
    description: "Startup, product, venture, and platform reporting from TechCrunch.",
    homepageUrl: "https://techcrunch.com",
    feedUrl: "https://techcrunch.com/feed/",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "probationary",
    validationStatus: "unverified",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
  },
  {
    id: "ars-technica",
    name: "Ars Technica",
    topicLabel: "AI",
    description: "Deep technology, science, and computing coverage from Ars Technica.",
    homepageUrl: "https://arstechnica.com",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "active_default",
    validationStatus: "validated",
    mvpDefaultAllowed: true,
    editorialPreference: "approved",
    note: "Validated again on 2026-04-22. Existing runtime-default strict technology source.",
  },
  {
    id: "financial-times-global-economy",
    name: "Financial Times Global Economy",
    topicLabel: "Economics",
    description: "Narrower Financial Times coverage focused on macroeconomic and global economy reporting.",
    homepageUrl: "https://www.ft.com/global-economy",
    feedUrl: "https://www.ft.com/global-economy?format=rss",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "probationary",
    validationStatus: "validated",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Validated on 2026-04-19. Near-duplicate of the broad Financial Times runtime default; use only if targeted economics coverage is intentionally enabled.",
  },
  {
    id: "mit-technology-review",
    name: "MIT Technology Review",
    topicLabel: "Technology",
    description: "Research-grounded technology and AI coverage from MIT Technology Review.",
    homepageUrl: "https://www.technologyreview.com",
    feedUrl: "https://www.technologyreview.com/feed/",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "active_default",
    validationStatus: "validated",
    mvpDefaultAllowed: true,
    editorialPreference: "none",
    note: "Validated again on 2026-04-22. Strict technology source activated for public ingestion; donor runtime remains probationary until the MIT review path is retired.",
  },
  {
    id: "foreign-affairs",
    name: "Foreign Affairs",
    topicLabel: "Geopolitics",
    description: "Foreign policy and geopolitical analysis from Foreign Affairs.",
    homepageUrl: "https://www.foreignaffairs.com",
    feedUrl: "https://www.foreignaffairs.com/rss.xml",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "active_default",
    validationStatus: "validated",
    mvpDefaultAllowed: true,
    editorialPreference: "none",
    note: "Validated again on 2026-04-22. Strict politics/geopolitics source activated for public ingestion.",
  },
  {
    id: "the-diplomat",
    name: "The Diplomat",
    topicLabel: "Geopolitics",
    description: "Asia-Pacific geopolitics, policy, and regional analysis from The Diplomat.",
    homepageUrl: "https://thediplomat.com",
    feedUrl: "https://thediplomat.com/feed",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "active_default",
    validationStatus: "validated",
    mvpDefaultAllowed: true,
    editorialPreference: "none",
    note: "Validated again on 2026-04-22. Strict politics/geopolitics source activated for public ingestion.",
  },
  {
    id: "npr-world",
    name: "NPR World",
    topicLabel: "Geopolitics",
    description: "World coverage from NPR's public RSS feed.",
    homepageUrl: "https://www.npr.org/sections/world/",
    feedUrl: "https://feeds.npr.org/1004/rss.xml",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "active_default",
    validationStatus: "validated",
    mvpDefaultAllowed: true,
    editorialPreference: "none",
    note: "Validated again on 2026-04-22. Strict politics/geopolitics source activated for public ingestion.",
  },
  {
    id: "brookings-research",
    name: "Brookings Research",
    topicLabel: "Mixed-domain",
    description: "Cross-domain research and commentary from Brookings.",
    homepageUrl: "https://www.brookings.edu/research/",
    feedUrl: "https://www.brookings.edu/feeds/rss/research/",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "disabled",
    validationStatus: "failed",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Rechecked on 2026-04-22. Supplied URL redirects to an HTML research page and fails RSS parsing, so it is registered as mixed-domain/O3 but not actively fetched.",
  },
  {
    id: "foreign-policy",
    name: "Foreign Policy",
    topicLabel: "Mixed-domain",
    description: "Foreign policy, geopolitical, and international affairs reporting from Foreign Policy.",
    homepageUrl: "https://foreignpolicy.com",
    feedUrl: "https://foreignpolicy.com/feed",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "active_default",
    validationStatus: "validated",
    mvpDefaultAllowed: true,
    editorialPreference: "none",
    note: "Validated again on 2026-04-22. Activated as mixed-domain/O3; item content, not source name alone, decides homepage category.",
  },
  {
    id: "guardian-world",
    name: "The Guardian World",
    topicLabel: "Mixed-domain",
    description: "Broad global news coverage from The Guardian's world feed.",
    homepageUrl: "https://www.theguardian.com/world",
    feedUrl: "https://www.theguardian.com/world/rss",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "active_default",
    validationStatus: "validated",
    mvpDefaultAllowed: true,
    editorialPreference: "none",
    note: "Validated again on 2026-04-22. Activated as mixed-domain/O3; item content, not source name alone, decides homepage category.",
  },
  {
    id: "hacker-news-best",
    name: "Hacker News Best",
    topicLabel: "Technology",
    description: "Community-curated technology and startup links from Hacker News Best.",
    homepageUrl: "https://news.ycombinator.com",
    feedUrl: "https://hnrss.org/best",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "ready",
    lifecycleStatus: "active_default",
    validationStatus: "validated",
    mvpDefaultAllowed: true,
    editorialPreference: "none",
    note: "Validated again on 2026-04-22. Strict technology source activated for public ingestion.",
  },
  {
    id: "csis-analysis",
    name: "CSIS Analysis",
    topicLabel: "Mixed-domain",
    description: "Cross-domain strategic analysis from CSIS.",
    homepageUrl: "https://www.csis.org/analysis",
    feedUrl: "https://www.csis.org/analysis/feed",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "disabled",
    validationStatus: "failed",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Rechecked on 2026-04-22. Supplied endpoint returns 404 and fails RSS parsing, so it is registered as mixed-domain/O3 but not actively fetched.",
  },
  {
    id: "the-news-api-top",
    name: "TheNewsAPI Top News",
    topicLabel: "Markets",
    description: "Top U.S. business and technology headlines via TheNewsAPI.",
    homepageUrl: "https://www.thenewsapi.com",
    feedUrl: "thenewsapi://api.thenewsapi.com/v1/news/top?locale=us&language=en&categories=business,tech&limit=15",
    cadence: "Near real-time",
    sourceType: "news",
    sourceFormat: "api",
    importStatus: "manual",
    lifecycleStatus: "probationary",
    validationStatus: "requires_key",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Requires THE_NEWS_API_KEY or NEWS_API_KEY in the environment before the importer can fetch articles successfully.",
  },
  {
    id: "gdelt-finance-monitor",
    name: "GDELT Finance Monitor",
    topicLabel: "Markets",
    description: "A rolling GDELT RSS query covering finance, Fed, inflation, and earnings language.",
    homepageUrl: "https://www.gdeltproject.org",
    feedUrl:
      "https://api.gdeltproject.org/api/v2/doc/doc?query=(market%20OR%20stocks%20OR%20fed%20OR%20inflation%20OR%20earnings)&mode=artlist&maxrecords=25&timespan=1day&sort=datedesc&format=rss",
    cadence: "Near real-time",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "probationary",
    validationStatus: "unverified",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "GDELT query feeds are discovery inputs, not MVP backbone sources. Validate rate-limit behavior before import.",
  },
  {
    id: "ap-top-news",
    name: "AP Top News",
    topicLabel: "Geopolitics",
    description: "Global breaking news from Associated Press.",
    homepageUrl: "https://apnews.com",
    feedUrl: "https://apnews.com/hub/apf-topnews?output=rss",
    cadence: "Daily",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "legacy",
    validationStatus: "failed",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "Current AP URL is not validated for parser import. Do not promote without a fresh working endpoint check.",
  },

  {
    id: "gdelt-ai-monitor",
    name: "GDELT AI Monitor",
    topicLabel: "AI",
    description: "Global AI-related news via GDELT query.",
    homepageUrl: "https://www.gdeltproject.org",
    feedUrl:
      "https://api.gdeltproject.org/api/v2/doc/doc?query=artificial%20intelligence&mode=artlist&maxrecords=25&timespan=1day&sort=datedesc&format=rss",
    cadence: "Near real-time",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "probationary",
    validationStatus: "unverified",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "GDELT query feeds are discovery inputs, not MVP backbone sources. Validate rate-limit behavior before import.",
  },

  {
    id: "gdelt-geopolitics-monitor",
    name: "GDELT Geopolitics",
    topicLabel: "Geopolitics",
    description: "Global geopolitics coverage via GDELT.",
    homepageUrl: "https://www.gdeltproject.org",
    feedUrl:
      "https://api.gdeltproject.org/api/v2/doc/doc?query=china%20OR%20us%20OR%20war%20OR%20election&mode=artlist&maxrecords=25&timespan=1day&sort=datedesc&format=rss",
    cadence: "Near real-time",
    sourceType: "news",
    sourceFormat: "rss",
    importStatus: "manual",
    lifecycleStatus: "probationary",
    validationStatus: "unverified",
    mvpDefaultAllowed: false,
    editorialPreference: "none",
    note: "GDELT query feeds are discovery inputs, not MVP backbone sources. Validate rate-limit behavior before import.",
  },
];
