import type { RawItem } from "@/lib/models/raw-item";

export const seedRawItems: RawItem[] = [
  {
    id: "seed-1",
    source: "Reuters World",
    title: "Chip export controls tighten as U.S. expands AI hardware restrictions",
    url: "https://example.com/reuters-chip-controls",
    published_at: "2026-04-18T07:10:00.000Z",
    raw_content: "U.S. officials widened export controls on advanced AI chips, prompting suppliers and cloud providers to reassess near-term shipments.",
  },
  {
    id: "seed-2",
    source: "Ars Technica",
    title: "AI chip suppliers adjust plans after fresh export restrictions",
    url: "https://example.com/ars-chip-controls",
    published_at: "2026-04-18T07:35:00.000Z",
    raw_content: "Chipmakers and hyperscalers are adjusting procurement plans after a tighter export regime for advanced accelerators.",
  },
  {
    id: "seed-3",
    source: "MarketWatch",
    title: "Fed officials signal rates may stay higher as inflation cools unevenly",
    url: "https://example.com/marketwatch-fed-rates",
    published_at: "2026-04-18T06:20:00.000Z",
    raw_content: "Federal Reserve officials said rates may need to stay restrictive longer because inflation is easing at an uneven pace across core sectors.",
  },
  {
    id: "seed-4",
    source: "Reuters Business",
    title: "Investors reassess rate-cut bets after Fed officials strike cautious tone",
    url: "https://example.com/reuters-fed-rates",
    published_at: "2026-04-18T06:50:00.000Z",
    raw_content: "Bond traders pared back aggressive rate-cut expectations after several Fed officials emphasized sticky services inflation.",
  },
  {
    id: "seed-5",
    source: "Associated Press",
    title: "European leaders debate emergency energy support after shipping disruption",
    url: "https://example.com/ap-energy-support",
    published_at: "2026-04-18T05:40:00.000Z",
    raw_content: "European officials are weighing emergency support measures after shipping disruption pushed fuel delivery costs higher.",
  },
  {
    id: "seed-6",
    source: "Reuters World",
    title: "Fuel costs rise as Europe weighs emergency response to shipping disruption",
    url: "https://example.com/reuters-energy-support",
    published_at: "2026-04-18T05:55:00.000Z",
    raw_content: "Shipping disruption is raising fuel and insurance costs, forcing European governments to consider targeted relief.",
  },
  {
    id: "seed-7",
    source: "The Verge",
    title: "Satellite internet providers rush capacity upgrades after regional outage",
    url: "https://example.com/verge-satellite-outage",
    published_at: "2026-04-18T04:45:00.000Z",
    raw_content: "Satellite operators accelerated capacity plans after a regional outage exposed resilience gaps for enterprise connectivity customers.",
  },
  {
    id: "seed-8",
    source: "Associated Press",
    title: "Regional outage pushes satellite providers to expand backup capacity",
    url: "https://example.com/ap-satellite-outage",
    published_at: "2026-04-18T04:58:00.000Z",
    raw_content: "A regional communications outage is prompting satellite providers to expand backup capacity and improve failover readiness.",
  },
  {
    id: "seed-9",
    source: "Reuters Business",
    title: "EV suppliers brace for new tariff review as trade tensions rise",
    url: "https://example.com/reuters-ev-tariffs",
    published_at: "2026-04-18T03:25:00.000Z",
    raw_content: "Electric vehicle suppliers are preparing for a new tariff review that could reshape import costs for batteries and power electronics.",
  },
  {
    id: "seed-10",
    source: "MarketWatch",
    title: "Trade review puts EV battery supply chain costs back in focus",
    url: "https://example.com/marketwatch-ev-tariffs",
    published_at: "2026-04-18T03:42:00.000Z",
    raw_content: "Automotive investors are watching a tariff review that could raise costs for EV batteries, inverters, and other imported components.",
  },
];
