import type { DonorDefinition } from "@/adapters/donors/types";

export const openclawDefinition: DonorDefinition = {
  donor: "openclaw",
  displayName: "openclaw-newsroom",
  summary: "Ingestion-ops donor that contributes feed transport and source metadata patterns.",
  transformationBoundary:
    "openclaw contributes feed discovery and ingestion shell patterns, while the website keeps canonical RawItem generation.",
  contractStates: {
    ingestion: "active",
    clustering: "stubbed",
    ranking: "stubbed",
    connection: "stubbed",
    enrichment: "future_ready",
  },
  feeds: [
    {
      id: "openclaw-the-verge",
      donor: "openclaw",
      source: "The Verge",
      homepageUrl: "https://www.theverge.com",
      topic: "Tech",
      domainScope: "strict",
      defaultCategory: "tech",
      credibility: 74,
      reliability: 0.74,
      sourceClass: "specialist_press",
      trustTier: "tier_2",
      provenance: "specialist_analysis",
      status: "active",
      availability: "default",
      fetch: {
        feedUrl: "https://www.theverge.com/rss/index.xml",
        timeoutMs: 4500,
        retryCount: 1,
        maxItems: 6,
      },
    },
    {
      id: "openclaw-ars-technica",
      donor: "openclaw",
      source: "Ars Technica",
      homepageUrl: "https://arstechnica.com",
      topic: "Tech",
      domainScope: "strict",
      defaultCategory: "tech",
      credibility: 81,
      reliability: 0.8,
      sourceClass: "specialist_press",
      trustTier: "tier_1",
      provenance: "specialist_analysis",
      status: "active",
      availability: "default",
      fetch: {
        feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
        timeoutMs: 4500,
        retryCount: 1,
        maxItems: 6,
      },
    },
    {
      id: "mit-technology-review",
      donor: "openclaw",
      source: "MIT Technology Review",
      homepageUrl: "https://www.technologyreview.com",
      topic: "Tech",
      domainScope: "strict",
      defaultCategory: "tech",
      credibility: 82,
      reliability: 0.82,
      sourceClass: "specialist_press",
      trustTier: "tier_2",
      provenance: "specialist_analysis",
      status: "active",
      availability: "probationary",
      fetch: {
        feedUrl: "https://www.technologyreview.com/feed/",
        timeoutMs: 4500,
        retryCount: 1,
        maxItems: 4,
      },
    },
    {
      id: "foreign-affairs",
      donor: "openclaw",
      source: "Foreign Affairs",
      homepageUrl: "https://www.foreignaffairs.com",
      topic: "World",
      domainScope: "strict",
      defaultCategory: "politics",
      credibility: 86,
      reliability: 0.84,
      sourceClass: "specialist_press",
      trustTier: "tier_1",
      provenance: "specialist_analysis",
      status: "active",
      availability: "default",
      fetch: {
        feedUrl: "https://www.foreignaffairs.com/rss.xml",
        timeoutMs: 5000,
        retryCount: 1,
        maxItems: 5,
      },
    },
    {
      id: "the-diplomat",
      donor: "openclaw",
      source: "The Diplomat",
      homepageUrl: "https://thediplomat.com",
      topic: "World",
      domainScope: "strict",
      defaultCategory: "politics",
      credibility: 80,
      reliability: 0.8,
      sourceClass: "specialist_press",
      trustTier: "tier_2",
      provenance: "specialist_analysis",
      status: "active",
      availability: "default",
      fetch: {
        feedUrl: "https://thediplomat.com/feed",
        timeoutMs: 5000,
        retryCount: 1,
        maxItems: 5,
      },
    },
    {
      id: "npr-world",
      donor: "openclaw",
      source: "NPR World",
      homepageUrl: "https://www.npr.org/sections/world/",
      topic: "World",
      domainScope: "strict",
      defaultCategory: "politics",
      credibility: 84,
      reliability: 0.84,
      sourceClass: "general_newswire",
      trustTier: "tier_1",
      provenance: "primary_reporting",
      status: "active",
      availability: "default",
      fetch: {
        feedUrl: "https://feeds.npr.org/1004/rss.xml",
        timeoutMs: 5000,
        retryCount: 1,
        maxItems: 5,
      },
    },
    {
      id: "foreign-policy",
      donor: "openclaw",
      source: "Foreign Policy",
      homepageUrl: "https://foreignpolicy.com",
      topic: "World",
      domainScope: "mixed_domain",
      credibility: 82,
      reliability: 0.81,
      sourceClass: "specialist_press",
      trustTier: "tier_2",
      provenance: "specialist_analysis",
      status: "active",
      availability: "default",
      fetch: {
        feedUrl: "https://foreignpolicy.com/feed",
        timeoutMs: 5000,
        retryCount: 1,
        maxItems: 5,
      },
    },
    {
      id: "guardian-world",
      donor: "openclaw",
      source: "The Guardian World",
      homepageUrl: "https://www.theguardian.com/world",
      topic: "World",
      domainScope: "mixed_domain",
      credibility: 80,
      reliability: 0.8,
      sourceClass: "general_newswire",
      trustTier: "tier_2",
      provenance: "primary_reporting",
      status: "active",
      availability: "default",
      fetch: {
        feedUrl: "https://www.theguardian.com/world/rss",
        timeoutMs: 5000,
        retryCount: 1,
        maxItems: 5,
      },
    },
    {
      id: "hacker-news-best",
      donor: "openclaw",
      source: "Hacker News Best",
      homepageUrl: "https://news.ycombinator.com",
      topic: "Tech",
      domainScope: "strict",
      defaultCategory: "tech",
      credibility: 68,
      reliability: 0.68,
      sourceClass: "specialist_press",
      trustTier: "tier_3",
      provenance: "specialist_analysis",
      status: "active",
      availability: "default",
      fetch: {
        feedUrl: "https://hnrss.org/best",
        timeoutMs: 5000,
        retryCount: 1,
        maxItems: 5,
      },
    },
    {
      id: "brookings-research",
      donor: "openclaw",
      source: "Brookings Research",
      homepageUrl: "https://www.brookings.edu/research/",
      topic: "World",
      domainScope: "mixed_domain",
      credibility: 82,
      reliability: 0.78,
      sourceClass: "specialist_press",
      trustTier: "tier_2",
      provenance: "specialist_analysis",
      status: "inactive",
      availability: "probationary",
      fetch: {
        feedUrl: "https://www.brookings.edu/feeds/rss/research/",
        timeoutMs: 5000,
        retryCount: 1,
        maxItems: 5,
      },
    },
    {
      id: "csis-analysis",
      donor: "openclaw",
      source: "CSIS Analysis",
      homepageUrl: "https://www.csis.org/analysis",
      topic: "World",
      domainScope: "mixed_domain",
      credibility: 82,
      reliability: 0.78,
      sourceClass: "specialist_press",
      trustTier: "tier_2",
      provenance: "specialist_analysis",
      status: "inactive",
      availability: "probationary",
      fetch: {
        feedUrl: "https://www.csis.org/analysis/feed",
        timeoutMs: 5000,
        retryCount: 1,
        maxItems: 5,
      },
    },
  ],
};
